import { accountParent } from "./accounts";

export const accountChild: accountParent [] = [ 
    {
    id: 1 ,
    firstName:'Leomar',
    lastName:'Wandas',
    middleName: 'Mines',
    username: 'leo@gmail.com',
    password: '1234',
    accountType: 'Admin',
    businessType: 'Clothing',
    houseNo: 'D202',
    city: 'Baguio',
    stateProvince: 'Benguet',
    Country: 'Philippines',
    zip: 2601,
    },
    {
        id: 2 ,
        firstName:'Terio',
        lastName:'Wakat',
        middleName: 'Devera',
        username: 'terio@gmail.com',
        password: '1234',
        accountType: 'CEO',
        businessType: 'Foods',
        houseNo: 'CA02',
    city: 'Baguio',
    stateProvince: 'Benguet',
    Country: 'Philippines',
    zip: 2600,
        },
        {
            id: 1 ,
            firstName:'Leomar',
            lastName:'Wandas',
            middleName: 'Mines',
            username: 'leo@gmail.com',
            password: '1234',
            accountType: 'Buyer',
            businessType: 'Movies',
            houseNo: 'FA-312',
            city: 'Baguio',
            stateProvince: 'Benguet',
            Country: 'Philippines',
            zip: 2605,
        },
        {
            id: 4 ,
            firstName:'Leomar',
            lastName:'Wandas',
            middleName: 'Mines',
            username: 'leo@gmail.com',
            password: '1234',
            accountType: 'Admin',
            businessType: 'Clothing',
            houseNo: 'D202',
            city: 'Baguio',
            stateProvince: 'Benguet',
            Country: 'Philippines',
            zip: 2601,
            },

            {
                id: 5 ,
                firstName:'Terio',
                lastName:'Wakat',
                middleName: 'Devera',
                username: 'terio@gmail.com',
                password: '1234',
                accountType: 'CEO',
                businessType: 'Foods',
                houseNo: 'CA02',
            city: 'Baguio',
            stateProvince: 'Benguet',
            Country: 'Philippines',
            zip: 2600,
                },

]