import { clothParent } from './clothing';

export const clothChild: clothParent[] = [
    { id: 1,
    category: 'Jacket',
    brand: 'Fubu',
    size: 'Large',
    color: 'Black',
    prize: '20 pesos',
    country: 'Philippines',

    },
    { id: 2,
        category: 'T-Shirt',
        brand: 'Nike',
        size: 'Medium',
        color: 'Black',
        prize: '80 pesos',
        country: 'USA',
    },

    { id: 3,
        category: 'Long Sleeves',
        brand: 'New',
        size: 'Extra Large',
        color: 'Black',
        prize: '800 pesos',
        country: 'USA',
    },
    { id: 4,
        category: 'Pants',
        brand: 'Penshoppe',
        size: 'Small',
        color: 'Blue',
        prize: '900 pesos',
        country: 'Philippines',
    },
    { id: 5,
        category: 'Polo',
        brand: 'Fubu',
        size: 'small',
        color: 'Green',
        prize: '1200 pesos',
        country: 'Philippines',
    },
]